version: "3"

services:
  mongodb_burger: 
    image: mongodb/mongodb-community-server:7.0.2-ubuntu2204
    container_name: mongodb_burger
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ~/docker_data/mongo:/data/db
    networks:
      - backend_burger_network

networks:
  backend_burger_network:
    name: backend_burger_network
    external: true